local typeMaps = mjrequire "common/typeMaps"

local resource = {}

local sapienInventory = mjrequire "common/sapienInventory"
local snapGroup = mjrequire "common/snapGroup"

local locale = mjrequire "common/locale"
local gameObjectTypeIndexMap = typeMaps.types.gameObject
local skillTypeIndexMap = typeMaps.types.skill

resource.types = typeMaps:createMap("resource", {
    {
        key = "branch",
        name = locale:get("resource_branch"),
        plural = locale:get("resource_branch_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchBranch,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
		placeBuildableMaleSnapPoints = snapGroup.malePoints.horizontalColumnMaleSnapPoints,
    },
    {
        key = "log",
        name = locale:get("resource_log"),
        plural = locale:get("resource_log_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchLog,
		placeBuildableMaleSnapPoints = snapGroup.malePoints.horizontalColumnMaleSnapPoints,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "rock",
        name = locale:get("resource_rock"),
        plural = locale:get("resource_rock_plural"),
        nameGeneric = locale:get("resource_rockGeneric"),
        pluralGeneric = locale:get("resource_rockGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.rock,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "rockSoft",
        name = locale:get("resource_rockSoft"),
        plural = locale:get("resource_rockSoft_plural"),
        nameGeneric = locale:get("resource_rockGeneric"),
        pluralGeneric = locale:get("resource_rockGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.limestoneRock,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "apple",
        name = locale:get("fruit_apple"),
        plural = locale:get("fruit_apple_plural"),
        foodValue = 0.5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.apple,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "appleRotten",
        name = locale:get("fruit_apple_rotten"),
        plural = locale:get("fruit_apple_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.appleRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "elderberry",
        name = locale:get("fruit_elderberry"),
        plural = locale:get("fruit_elderberry_plural"),
        foodValue = 0.3,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.elderberry,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "elderberryRotten",
        name = locale:get("fruit_elderberry_rotten"),
        plural = locale:get("fruit_elderberry_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.elderberryRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "orange",
        name = locale:get("fruit_orange"),
        plural = locale:get("fruit_orange_plural"),
        foodValue = 0.5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.orange,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "orangeRotten",
        name = locale:get("fruit_orange_rotten"),
        plural = locale:get("fruit_orange_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.orangeRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "peach",
        name = locale:get("fruit_peach"),
        plural = locale:get("fruit_peach_plural"),
        foodValue = 0.5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.peach,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "peachRotten",
        name = locale:get("fruit_peach_rotten"),
        plural = locale:get("fruit_peach_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.peachRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "banana",
        name = locale:get("fruit_banana"),
        plural = locale:get("fruit_banana_plural"),
        foodValue = 0.5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.banana,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "bananaRotten",
        name = locale:get("fruit_banana_rotten"),
        plural = locale:get("fruit_banana_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bananaRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "coconut",
        name = locale:get("fruit_coconut"),
        plural = locale:get("fruit_coconut_plural"),
        foodValue = 0.7,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.coconut,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "coconutRotten",
        name = locale:get("fruit_coconut_rotten"),
        plural = locale:get("fruit_coconut_rotten_plural"),
        compostValue = 3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.coconutRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "dirt",
        name = locale:get("resource_dirt"),
        plural = locale:get("resource_dirt_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.dirt,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "hay",
        name = locale:get("resource_hay"),
        plural = locale:get("resource_hay_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.hay,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "hayRotten",
        name = locale:get("resource_hayRotten"),
        plural = locale:get("resource_hayRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.hayRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "grass",
        name = locale:get("resource_grass"),
        plural = locale:get("resource_grass_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.grass,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "raspberry",
        name = locale:get("fruit_raspberry"),
        plural = locale:get("fruit_raspberry_plural"),
        foodValue = 0.3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.raspberry,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "raspberryRotten",
        name = locale:get("fruit_raspberry_rotten"),
        plural = locale:get("fruit_raspberry_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.raspberryRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "gooseberry",
        name = locale:get("fruit_gooseberry"),
        plural = locale:get("fruit_gooseberry_plural"),
        foodValue = 0.3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.gooseberry,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "gooseberryRotten",
        name = locale:get("fruit_gooseberry_rotten"),
        plural = locale:get("fruit_gooseberry_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.gooseberryRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "pumpkin",
        name = locale:get("fruit_pumpkin"),
        plural = locale:get("fruit_pumpkin_plural"),
        foodValue = 0.4,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pumpkin,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "pumpkinRotten",
        name = locale:get("fruit_pumpkin_rotten"),
        plural = locale:get("fruit_pumpkin_rotten_plural"),
        compostValue = 4,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pumpkinRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "pumpkinCooked",
        name = locale:get("resource_pumpkinCooked"),
        plural = locale:get("resource_pumpkinCooked_plural"),
        foodValue = 0.8,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pumpkinCooked,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "beetroot",
        name = locale:get("fruit_beetroot"),
        plural = locale:get("fruit_beetroot_plural"),
        foodValue = 0.3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetroot,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5
    },
    {
        key = "beetrootRotten",
        name = locale:get("fruit_beetroot_rotten"),
        plural = locale:get("fruit_beetroot_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetrootRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "beetrootCooked",
        name = locale:get("resource_beetrootCooked"),
        plural = locale:get("resource_beetrootCooked_plural"),
        foodValue = 0.6,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetrootCooked,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "beetrootSeed",
        name = locale:get("fruit_beetrootSeed"),
        plural = locale:get("fruit_beetrootSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetrootSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "beetrootSeedRotten",
        name = locale:get("fruit_beetrootSeed_rotten"),
        plural = locale:get("fruit_beetrootSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetrootSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "gingerRoot",
        name = locale:get("fruit_gingerRoot"),
        plural = locale:get("fruit_gingerRoot_plural"),
        foodValue = 0.1,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.gingerRoot,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "gingerRootRotten",
        name = locale:get("fruit_gingerRoot_rotten"),
        plural = locale:get("fruit_gingerRoot_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.gingerRootRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "turmericRoot",
        name = locale:get("fruit_turmericRoot"),
        plural = locale:get("fruit_turmericRoot_plural"),
        foodValue = 0.1,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.turmericRoot,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "turmericRootRotten",
        name = locale:get("fruit_turmericRoot_rotten"),
        plural = locale:get("fruit_turmericRoot_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.turmericRootRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "garlic",
        name = locale:get("fruit_garlic"),
        plural = locale:get("fruit_garlic_plural"),
        foodValue = 0.1,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.garlic,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "garlicRotten",
        name = locale:get("fruit_garlic_rotten"),
        plural = locale:get("fruit_garlic_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.garlicRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "wheat",
        name = locale:get("fruit_wheat"),
        plural = locale:get("fruit_wheat_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.wheat,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "wheatRotten",
        name = locale:get("fruit_wheat_rotten"),
        plural = locale:get("fruit_wheat_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.wheatRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "flax",
        name = locale:get("fruit_flax"),
        plural = locale:get("fruit_flax_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flax,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "flaxDried",
        name = locale:get("resource_flaxDried"),
        plural = locale:get("resource_flaxDried_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flaxDried,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "flaxRotten",
        name = locale:get("fruit_flax_rotten"),
        plural = locale:get("fruit_flax_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flaxRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "flaxSeed",
        name = locale:get("fruit_flaxSeed"),
        plural = locale:get("fruit_flaxSeed_plural"),
        foodValue = 0.1,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flaxSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "flaxSeedRotten",
        name = locale:get("fruit_flaxSeed_rotten"),
        plural = locale:get("fruit_flaxSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flaxSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "poppyFlower",
        name = locale:get("fruit_poppyFlower"),
        plural = locale:get("fruit_poppyFlower_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.poppyFlower,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "poppyFlowerRotten",
        name = locale:get("fruit_poppyFlower_rotten"),
        plural = locale:get("fruit_poppyFlower_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.poppyFlowerRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "echinaceaFlower",
        name = locale:get("fruit_echinaceaFlower"),
        plural = locale:get("fruit_echinaceaFlower_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.echinaceaFlower,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "echinaceaFlowerRotten",
        name = locale:get("fruit_echinaceaFlower_rotten"),
        plural = locale:get("fruit_echinaceaFlower_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.echinaceaFlowerRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "marigoldFlower",
        name = locale:get("fruit_marigoldFlower"),
        plural = locale:get("fruit_marigoldFlower_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.marigoldFlower,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "marigoldFlowerRotten",
        name = locale:get("fruit_marigoldFlower_rotten"),
        plural = locale:get("fruit_marigoldFlower_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.marigoldFlowerRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "aloeLeaf",
        name = locale:get("fruit_aloeLeaf"),
        plural = locale:get("fruit_aloeLeaf_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aloeLeaf,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "aloeLeafRotten",
        name = locale:get("fruit_aloeLeaf_rotten"),
        plural = locale:get("fruit_aloeLeaf_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aloeLeafRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "sunflowerSeed",
        name = locale:get("fruit_sunflowerSeed"),
        plural = locale:get("fruit_sunflowerSeed_plural"),
        foodValue = 0.1,
        defaultToEatingDisabled = true,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.sunflowerSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "sunflowerSeedRotten",
        name = locale:get("fruit_sunflowerSeed_rotten"),
        plural = locale:get("fruit_sunflowerSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.sunflowerSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "sand",
        name = locale:get("resource_sand"),
        plural = locale:get("resource_sand_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.sand,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "rockSmall", --hard
        name = locale:get("resource_rockSmall"),
        plural = locale:get("resource_rockSmall_plural"),
        nameGeneric = locale:get("resource_rockSmallGeneric"),
        pluralGeneric = locale:get("resource_rockSmallGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.rockSmall,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "rockSmallSoft",
        name = locale:get("resource_rockSmallSoft"),
        plural = locale:get("resource_rockSmallSoft_plural"),
        nameGeneric = locale:get("resource_rockSmallGeneric"),
        pluralGeneric = locale:get("resource_rockSmallGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.sandstoneYellowRockSmall,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "flint",
        name = locale:get("resource_flint"),
        plural = locale:get("resource_flint_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flint,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "clay",
        name = locale:get("resource_clay"),
        plural = locale:get("resource_clay_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.clay,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "copperOre",
        name = locale:get("resource_copperOre"),
        plural = locale:get("resource_copperOre_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.copperOre,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 8,
    },
    {
        key = "tinOre",
        name = locale:get("resource_tinOre"),
        plural = locale:get("resource_tinOre_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.tinOre,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 8,
    },
    {
        key = "deadChicken",
        name = locale:get("resource_deadChicken"),
        plural = locale:get("resource_deadChicken_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.deadChicken,
        disallowsDecorationPlacing = true,
        impactCausesInjury = true,
        tradeBatchSize = 2,
        tradeValue = 4,
    },
    {
        key = "deadChickenRotten",
        name = locale:get("resource_deadChickenRotten"),
        plural = locale:get("resource_deadChickenRotten_plural"),
        compostValue = 3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.deadChicken,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 2,
        tradeValue = 1,
    },
    {
        key = "deadAlpaca",
        name = locale:get("resource_deadAlpaca"),
        plural = locale:get("resource_deadAlpaca_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.deadAlpaca,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 1,
        tradeValue = 10,
    },
    {
        key = "chickenMeat",
        name = locale:get("resource_chickenMeat"),
        plural = locale:get("resource_chickenMeat_plural"),
        foodValue = 0.5,
        foodPortionCount = 2,
        defaultToEatingDisabled = true,
        foodPoisoningChance = 0.8,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.chickenMeat,
		isRawMeatForTutorial = true,
        impactCausesInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "chickenMeatCooked",
        name = locale:get("resource_chickenMeatCooked"),
        plural = locale:get("resource_chickenMeatCooked_plural"),
        foodValue = 0.7,
        foodPortionCount = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.chickenMeatCooked,
		isCookedMeatForTutorial = true,
        impactCausesInjury = true,
        tradeBatchSize = 10,
        tradeValue = 10,
    },
    {
        key = "alpacaMeat",
        name = locale:get("resource_alpacaMeat"),
        plural = locale:get("resource_alpacaMeat_plural"),
        foodValue = 0.5,
        foodPortionCount = 3,
        defaultToEatingDisabled = true,
        foodPoisoningChance = 0.2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.alpacaMeatRack,
		isRawMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 12,
    },
    {
        key = "alpacaMeatCooked",
        name = locale:get("resource_alpacaMeatCooked"),
        plural = locale:get("resource_alpacaMeatCooked_plural"),
        foodValue = 0.7,
        foodPortionCount = 3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.alpacaMeatRackCooked,
		isCookedMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 15,
    },
    {
        key = "mammothMeat",
        name = locale:get("resource_mammothMeat"),
        plural = locale:get("resource_mammothMeat_plural"),
        foodValue = 0.5,
        foodPortionCount = 4,
        defaultToEatingDisabled = true,
        foodPoisoningChance = 0.2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mammothMeatTBone,
		isRawMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 16,
    },
    {
        key = "mammothMeatCooked",
        name = locale:get("resource_mammothMeatCooked"),
        plural = locale:get("resource_mammothMeatCooked_plural"),
        foodValue = 0.7,
        foodPortionCount = 4,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mammothMeatTBoneCooked,
		isCookedMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 20,
    },
    {
        key = "fish",
        name = locale:get("resource_fish"),
        plural = locale:get("resource_fish_plural"),
        foodValue = 0.5,
        foodPortionCount = 3,
        foodPoisoningChance = 0.01,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.fishFillet,
		isRawMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 12,
    },
    {
        key = "fishCooked",
        name = locale:get("resource_fishCooked"),
        plural = locale:get("resource_fish_plural"),
        foodValue = 0.7,
        foodPortionCount = 3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.fishFilletCooked,
		isCookedMeatForTutorial = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 15,
    },
    {
        key = "swordfishDead",
        name = locale:get("resource_swordfishDead"),
        plural = locale:get("resource_swordfishDead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.swordfishDead,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 1,
        tradeValue = 12,
    },

    
    {
        key = "stoneSpear",
        name = locale:get("resource_stoneSpear"),
        plural = locale:get("resource_stoneSpear_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneSpear,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "stonePickaxe",
        name = locale:get("resource_stonePickaxe"),
        plural = locale:get("resource_stonePickaxe_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stonePickaxe,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "stoneHatchet",
        name = locale:get("resource_stoneHatchet"),
        plural = locale:get("resource_stoneHatchet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneHatchet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "bronzeHatchet",
        name = locale:get("resource_bronzeHatchet"),
        plural = locale:get("resource_bronzeHatchet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeHatchet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 6,
    },
    {
        key = "bronzePickaxe",
        name = locale:get("resource_bronzePickaxe"),
        plural = locale:get("resource_bronzePickaxe_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzePickaxe,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 6,
    },
    {
        key = "stoneSpearHead",
        name = locale:get("resource_stoneSpearHead"),
        plural = locale:get("resource_stoneSpearHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneSpearHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stonePickaxeHead",
        name = locale:get("resource_stonePickaxeHead"),
        plural = locale:get("resource_stonePickaxeHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stonePickaxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneAxeHead",
        name = locale:get("resource_stoneAxeHead"),
        plural = locale:get("resource_stoneAxeHead_plural"),
        nameGeneric = locale:get("resource_stoneAxeHeadGeneric"),
        pluralGeneric = locale:get("resource_stoneAxeHeadGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneAxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneAxeHeadSoft",
        name = locale:get("resource_stoneAxeHeadSoft"),
        plural = locale:get("resource_stoneAxeHeadSoft_plural"),
        nameGeneric = locale:get("resource_stoneAxeHeadGeneric"),
        pluralGeneric = locale:get("resource_stoneAxeHeadGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneAxeHead_limestone,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneKnife",
        name = locale:get("resource_stoneKnife"),
        plural = locale:get("resource_stoneKnife_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneKnife,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneChisel",
        name = locale:get("resource_stoneChisel"),
        plural = locale:get("resource_stoneChisel_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneChisel,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneHammerHead",
        name = locale:get("resource_stoneHammerHead"),
        plural = locale:get("resource_stoneHammerHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneHammerHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "stoneHammer",
        name = locale:get("resource_stoneHammer"),
        plural = locale:get("resource_stoneHammer_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneHammer,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "bronzeHammerHead",
        name = locale:get("resource_bronzeHammerHead"),
        plural = locale:get("resource_bronzeHammerHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeHammerHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "bronzeHammer",
        name = locale:get("resource_bronzeHammer"),
        plural = locale:get("resource_bronzeHammer_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeHammer,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 6,
    },
    
    {
        key = "flintSpear",
        name = locale:get("resource_flintSpear"),
        plural = locale:get("resource_flintSpear_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintSpear,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 9,
    },
    {
        key = "boneSpear",
        name = locale:get("resource_boneSpear"),
        plural = locale:get("resource_boneSpear_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.boneSpear,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 9,
    },
    {
        key = "bronzeSpear",
        name = locale:get("resource_bronzeSpear"),
        plural = locale:get("resource_bronzeSpear_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeSpear,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 6,
    },
    {
        key = "flintPickaxe",
        name = locale:get("resource_flintPickaxe"),
        plural = locale:get("resource_flintPickaxe_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintPickaxe,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 9,
    },
    {
        key = "flintHatchet",
        name = locale:get("resource_flintHatchet"),
        plural = locale:get("resource_flintHatchet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintHatchet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 9,
    },
    {
        key = "flintSpearHead",
        name = locale:get("resource_flintSpearHead"),
        plural = locale:get("resource_flintSpearHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintSpearHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "boneSpearHead",
        name = locale:get("resource_boneSpearHead"),
        plural = locale:get("resource_boneSpearHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.boneSpearHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "bronzeSpearHead",
        name = locale:get("resource_bronzeSpearHead"),
        plural = locale:get("resource_bronzeSpearHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeSpearHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "flintPickaxeHead",
        name = locale:get("resource_flintPickaxeHead"),
        plural = locale:get("resource_flintPickaxeHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintPickaxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "flintAxeHead",
        name = locale:get("resource_flintAxeHead"),
        plural = locale:get("resource_flintAxeHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintAxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "bronzePickaxeHead",
        name = locale:get("resource_bronzePickaxeHead"),
        plural = locale:get("resource_bronzePickaxeHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzePickaxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "bronzeAxeHead",
        name = locale:get("resource_bronzeAxeHead"),
        plural = locale:get("resource_bronzeAxeHead_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeAxeHead,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "flintKnife",
        name = locale:get("resource_flintKnife"),
        plural = locale:get("resource_flintKnife_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flintKnife,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "boneKnife",
        name = locale:get("resource_boneKnife"),
        plural = locale:get("resource_boneKnife_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.boneKnife,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "bronzeKnife",
        name = locale:get("resource_bronzeKnife"),
        plural = locale:get("resource_bronzeKnife_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeKnife,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "bronzeChisel",
        name = locale:get("resource_bronzeChisel"),
        plural = locale:get("resource_bronzeChisel_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeChisel,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "boneFlute",
        name = locale:get("resource_boneFlute"),
        plural = locale:get("resource_boneFlute_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.boneFlute,
        musicalInstrumentSkillTypeIndex = skillTypeIndexMap.flutePlaying,
        impactCausesInjury = true,
        tradeBatchSize = 5,
        tradeValue = 2,
    },
    {
        key = "logDrum",
        name = locale:get("resource_logDrum"),
        plural = locale:get("resource_logDrum_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.logDrum,
        musicalInstrumentSkillTypeIndex = skillTypeIndexMap.flutePlaying,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 2,
    },
    {
        key = "balafon",
        name = locale:get("resource_balafon"),
        plural = locale:get("resource_balafon_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.balafon,
        musicalInstrumentSkillTypeIndex = skillTypeIndexMap.flutePlaying,
        impactCausesMajorInjury = true,
        tradeBatchSize = 5,
        tradeValue = 8,
    },

    {
        key = "woodenPole",
        name = locale:get("resource_woodenPole"),
        plural = locale:get("resource_woodenPole_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchWoodenPole,
		placeBuildableMaleSnapPoints = snapGroup.malePoints.horizontalColumnMaleSnapPoints,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "splitLog",
        name = locale:get("resource_splitLog"),
        plural = locale:get("resource_splitLog_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchSplitLog,
		placeBuildableMaleSnapPoints = snapGroup.malePoints.horizontalColumnMaleSnapPoints,
        defaultToFuelDisabled = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 40,
        tradeValue = 5,
    },
    {
        key = "pineCone",
        name = locale:get("fruit_pineCone"),
        plural = locale:get("fruit_pineCone_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pineCone,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "pineConeBig",
        name = locale:get("fruit_pineConeBig"),
        plural = locale:get("fruit_pineConeBig_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pineConeBig,
        defaultToFuelDisabled = true,
        impactCausesInjury = true,
        tradeBatchSize = 2,
        tradeValue = 5,
    },
    {
        key = "pineConeRotten",
        name = locale:get("fruit_pineCone_rotten"),
        plural = locale:get("fruit_pineCone_rotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pineConeRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "pineConeBigRotten",
        name = locale:get("fruit_pineConeBig_rotten"),
        plural = locale:get("fruit_pineConeBig_rotten_plural"),
        compostValue = 3,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.pineConeBigRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 2,
        tradeValue = 1,
    },
    {
        key = "birchSeed",
        name = locale:get("fruit_birchSeed"),
        plural = locale:get("fruit_birchSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "birchSeedRotten",
        name = locale:get("fruit_birchSeed_rotten"),
        plural = locale:get("fruit_birchSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "aspenSeed",
        name = locale:get("fruit_aspenSeed"),
        plural = locale:get("fruit_aspenSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aspenSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "aspenSeedRotten",
        name = locale:get("fruit_aspenSeed_rotten"),
        plural = locale:get("fruit_aspenSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aspenSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "aspenBigSeed",
        name = locale:get("fruit_aspenBigSeed"),
        plural = locale:get("fruit_aspenBigSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aspenBigSeed,
        tradeBatchSize = 2,
        tradeValue = 5,
    },
    {
        key = "aspenBigSeedRotten",
        name = locale:get("fruit_aspenBigSeed_rotten"),
        plural = locale:get("fruit_aspenBigSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.aspenBigSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 2,
        tradeValue = 1,
    },
    {
        key = "willowSeed",
        name = locale:get("fruit_willowSeed"),
        plural = locale:get("fruit_willowSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.willowSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "willowSeedRotten",
        name = locale:get("fruit_willowSeed_rotten"),
        plural = locale:get("fruit_willowSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.willowSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "bambooSeed",
        name = locale:get("fruit_bambooSeed"),
        plural = locale:get("fruit_bambooSeed_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bambooSeed,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "bambooSeedRotten",
        name = locale:get("fruit_bambooSeed_rotten"),
        plural = locale:get("fruit_bambooSeed_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bambooSeedRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "woolskin",
        name = locale:get("resource_woolskin"),
        plural = locale:get("resource_woolskin_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.alpacaWoolskin,
        clothingInventoryLocation = sapienInventory.locations.torso.index,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "bone",
        name = locale:get("resource_bone"),
        plural = locale:get("resource_bone_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bone,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "burntBranch",
        name = locale:get("resource_burntBranch"),
        plural = locale:get("resource_burntBranch_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.burntBranch,
        impactCausesMajorInjury = true,
        tradeBatchSize = 2,
        tradeValue = 5,
    },
    {
        key = "unfiredUrnWet",
        name = locale:get("resource_unfiredUrnWet"),
        plural = locale:get("resource_unfiredUrnWet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnWet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "unfiredUrnDry",
        name = locale:get("resource_unfiredUrnDry"),
        plural = locale:get("resource_unfiredUrnDry_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnDry,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "firedUrn",
        name = locale:get("resource_firedUrn"),
        plural = locale:get("resource_firedUrn_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrn,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "unfiredUrnHulledWheat",
        name = locale:get("resource_unfiredUrnHulledWheat"),
        plural = locale:get("resource_unfiredUrnHulledWheat_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnHulledWheat,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 6,
    },
    {
        key = "unfiredUrnHulledWheatRotten",
        name = locale:get("resource_unfiredUrnHulledWheatRotten"),
        plural = locale:get("resource_unfiredUrnHulledWheatRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnHulledWheatRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "firedUrnHulledWheat",
        name = locale:get("resource_firedUrnHulledWheat"),
        plural = locale:get("resource_firedUrnHulledWheat_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnHulledWheat,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 8,
    },
    {
        key = "firedUrnHulledWheatRotten",
        name = locale:get("resource_firedUrnHulledWheatRotten"),
        plural = locale:get("resource_firedUrnHulledWheatRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnHulledWheatRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "quernstone",
        name = locale:get("resource_quernstone"),
        plural = locale:get("resource_quernstone_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.quernstone,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "unfiredUrnFlour",
        name = locale:get("resource_unfiredUrnFlour"),
        plural = locale:get("resource_unfiredUrnFlour_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnFlour,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 7,
    },
    {
        key = "unfiredUrnFlourRotten",
        name = locale:get("resource_unfiredUrnFlourRotten"),
        plural = locale:get("resource_unfiredUrnFlourRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredUrnFlourRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "firedUrnFlour",
        name = locale:get("resource_firedUrnFlour"),
        plural = locale:get("resource_firedUrnFlour_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnFlour,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 9,
    },
    {
        key = "firedUrnFlourRotten",
        name = locale:get("resource_firedUrnFlourRotten"),
        plural = locale:get("resource_firedUrnFlourRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnFlourRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "unfiredBowlWet",
        name = locale:get("resource_unfiredBowlWet"),
        plural = locale:get("resource_unfiredBowlWet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlWet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "unfiredBowlDry",
        name = locale:get("resource_unfiredBowlDry"),
        plural = locale:get("resource_unfiredBowlDry_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlDry,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "firedBowl",
        name = locale:get("resource_firedBowl"),
        plural = locale:get("resource_firedBowl_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowl,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "unfiredBowlInjuryMedicine",
        name = locale:get("resource_unfiredBowlInjuryMedicine"),
        plural = locale:get("resource_unfiredBowlInjuryMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlInjuryMedicine,
        isTopicalMedicine = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 10,
    },
    {
        key = "unfiredBowlBurnMedicine",
        name = locale:get("resource_unfiredBowlBurnMedicine"),
        plural = locale:get("resource_unfiredBowlBurnMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlBurnMedicine,
        isTopicalMedicine = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 10,
    },
    {
        key = "unfiredBowlFoodPoisoningMedicine",
        name = locale:get("resource_unfiredBowlFoodPoisoningMedicine"),
        plural = locale:get("resource_unfiredBowlFoodPoisoningMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlFoodPoisoningMedicine,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 10,
    },
    {
        key = "unfiredBowlVirusMedicine",
        name = locale:get("resource_unfiredBowlVirusMedicine"),
        plural = locale:get("resource_unfiredBowlVirusMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlVirusMedicine,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 10,
    },
    {
        key = "unfiredBowlMedicineRotten",
        name = locale:get("resource_unfiredBowlMedicineRotten"),
        plural = locale:get("resource_unfiredBowlMedicineRotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.unfiredBowlMedicineRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "firedBowlInjuryMedicine",
        name = locale:get("resource_firedBowlInjuryMedicine"),
        plural = locale:get("resource_firedBowlInjuryMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlInjuryMedicine,
        isTopicalMedicine = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 11,
    },
    {
        key = "firedBowlBurnMedicine",
        name = locale:get("resource_firedBowlBurnMedicine"),
        plural = locale:get("resource_firedBowlBurnMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlBurnMedicine,
        isTopicalMedicine = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 11,
    },
    {
        key = "firedBowlFoodPoisoningMedicine",
        name = locale:get("resource_firedBowlFoodPoisoningMedicine"),
        plural = locale:get("resource_firedBowlFoodPoisoningMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlFoodPoisoningMedicine,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 11,
    },
    {
        key = "firedBowlVirusMedicine",
        name = locale:get("resource_firedBowlVirusMedicine"),
        plural = locale:get("resource_firedBowlVirusMedicine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlVirusMedicine,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 11,
    },
    {
        key = "firedBowlMedicineRotten",
        name = locale:get("resource_firedBowlMedicineRotten"),
        plural = locale:get("resource_firedBowlMedicineRotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlMedicineRotten,
        disallowsDecorationPlacing = true,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "crucibleWet",
        name = locale:get("resource_crucibleWet"),
        plural = locale:get("resource_crucibleWet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.crucibleWet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "crucibleDry",
        name = locale:get("resource_crucibleDry"),
        plural = locale:get("resource_crucibleDry_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.crucibleDry,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 3,
    },
    {
        key = "branchRotten",
        name = locale:get("resource_branch_rotten"),
        plural = locale:get("resource_branch_rotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.branchRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 20,
        tradeValue = 1,
		placeBuildableMaleSnapPoints = snapGroup.malePoints.horizontalColumnMaleSnapPoints,
    },
    {
        key = "breadDough",
        name = locale:get("resource_breadDough"),
        plural = locale:get("resource_breadDough_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.breadDough,
        impactCausesInjury = true,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "breadDoughRotten",
        name = locale:get("resource_breadDoughRotten"),
        plural = locale:get("resource_breadDoughRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.breadDoughRotten,
        disallowsDecorationPlacing = true,
        impactCausesInjury = true,
        tradeBatchSize = 10,
        tradeValue = 1,
    },
    {
        key = "flaxTwine",
        name = locale:get("resource_flaxTwine"),
        plural = locale:get("resource_flaxTwine_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flaxTwine,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "flatbread",
        name = locale:get("resource_flatbread"),
        plural = locale:get("resource_flatbread_plural"),
        foodValue = 0.5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flatbread,
        tradeBatchSize = 25,
        tradeValue = 3,
    },
    {
        key = "flatbreadRotten",
        name = locale:get("resource_flatbreadRotten"),
        plural = locale:get("resource_flatbreadRotten_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.flatbreadRotten,
        disallowsDecorationPlacing = true,
        tradeBatchSize = 25,
        tradeValue = 1,
    },
    {
        key = "mudBrickWet",
        name = locale:get("resource_mudBrickWet"),
        plural = locale:get("resource_mudBrickWet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mudBrickWet_sand,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "mudBrickDry",
        name = locale:get("resource_mudBrickDry"),
        plural = locale:get("resource_mudBrickDry_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mudBrickDry_sand,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 6,
    },
    {
        key = "mudTileWet",
        name = locale:get("resource_mudTileWet"),
        plural = locale:get("resource_mudTileWet_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mudTileWet,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "mudTileDry",
        name = locale:get("resource_mudTileDry"),
        plural = locale:get("resource_mudTileDry_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.mudTileDry,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 3,
    },
    {
        key = "firedTile",
        name = locale:get("resource_firedTile"),
        plural = locale:get("resource_firedTile_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedTile,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 4,
    },
    {
        key = "firedBrick",
        name = locale:get("resource_firedBrick"),
        plural = locale:get("resource_firedBrick_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBrick_sand,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 7,
    },
    {
        key = "manure",
        name = locale:get("resource_manure"),
        plural = locale:get("resource_manure_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.manure,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "manureRotten",
        name = locale:get("resource_manureRotten"),
        plural = locale:get("resource_manureRotten_plural"),
        compostValue = 5,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.manureRotten,
        disallowsDecorationPlacing = true,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "rottenGoo",
        name = locale:get("resource_rottenGoo"),
        plural = locale:get("resource_rottenGoo_plural"),
        compostValue = 1,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.rottenGoo,
        disallowsDecorationPlacing = true,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "compost",
        name = locale:get("resource_compost"),
        plural = locale:get("resource_compost_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.compost,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 5,
    },
    {
        key = "compostRotten",
        name = locale:get("resource_compostRotten"),
        plural = locale:get("resource_compostRotten_plural"),
        compostValue = 2,
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.compostRotten,
        disallowsDecorationPlacing = true,
        impactCausesInjury = true,
        tradeBatchSize = 20,
        tradeValue = 1,
    },
    {
        key = "bronzeIngot",
        name = locale:get("resource_bronzeIngot"),
        plural = locale:get("resource_bronzeIngot_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.bronzeIngot,
        impactCausesMajorInjury = true,
        tradeBatchSize = 10,
        tradeValue = 5,
    },
    {
        key = "stoneBlockSoft",
        name = locale:get("resource_stoneBlockSoft"),
        plural = locale:get("resource_stoneBlockSoft_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.limestoneRockBlock,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 8,
    },
    {
        key = "stoneBlockHard",
        name = locale:get("resource_stoneBlockHard"),
        plural = locale:get("resource_stoneBlockHard_plural"),
        nameGeneric = locale:get("resource_stoneBlockGeneric"),
        pluralGeneric = locale:get("resource_stoneBlockGeneric_plural"),
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneBlock,
        impactCausesMajorInjury = true,
        tradeBatchSize = 20,
        tradeValue = 8,
    },
})

-- ^^^^^^^^^^^^^ WHEN ADDING RESOURCE TYPES: Dont forget to add to storage.lua ^^^^^^^^^^^^^

resource.groups = typeMaps:createMap("resourceGroup", {
    {
        key = "seed",
        name = locale:get("resource_group_seed"),
        plural = locale:get("resource_group_seed_plural"),
        resourceTypes = {},
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.beetrootSeed,
    },
    {
        key = "container",
        name = locale:get("resource_group_container"),
        plural = locale:get("resource_group_container_plural"),
        resourceTypes = {
            resource.types.unfiredUrnDry.index,
            resource.types.firedUrn.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrn,
    },
    {
        key = "bowl",
        name = locale:get("resource_group_bowl"),
        plural = locale:get("resource_group_bowl_plural"),
        resourceTypes = {
            resource.types.unfiredBowlDry.index,
            resource.types.firedBowl.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowl,
    },
    {
        key = "urnHulledWheat",
        name = locale:get("resource_group_urnHulledWheat"),
        plural = locale:get("resource_group_urnHulledWheat_plural"),
        resourceTypes = {
            resource.types.unfiredUrnHulledWheat.index,
            resource.types.firedUrnHulledWheat.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnHulledWheat,
    },
    {
        key = "urnFlour",
        name = locale:get("resource_group_urnFlour"),
        plural = locale:get("resource_group_urnFlour_plural"),
        resourceTypes = {
            resource.types.unfiredUrnFlour.index,
            resource.types.firedUrnFlour.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedUrnFlour,
    },
    {
        key = "campfireFuel",
        name = locale:get("resource_group_campfireFuel"),
        plural = locale:get("resource_group_campfireFuel_plural"),
        resourceTypes = {
            resource.types.branch.index,
            resource.types.log.index,
            resource.types.pineCone.index,
            resource.types.pineConeBig.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchBranch,
    },
    {
        key = "kilnFuel",
        name = locale:get("resource_group_kilnFuel"),
        plural = locale:get("resource_group_kilnFuel_plural"),
        resourceTypes = {
            resource.types.branch.index,
            resource.types.log.index,
            resource.types.pineCone.index,
            resource.types.pineConeBig.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.birchBranch,
    },
    {
        key = "torchFuel",
        name = locale:get("resource_group_torchFuel"),
        plural = locale:get("resource_group_torchFuel_plural"),
        resourceTypes = {
            resource.types.hay.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.hay,
    },
    {
        key = "brickBinder",
        name = locale:get("resource_group_brickBinder"),
        plural = locale:get("resource_group_brickBinder_plural"),
        resourceTypes = {
            resource.types.sand.index,
            resource.types.hay.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.sand,
    },
    {
        key = "injuryMedicine",
        name = locale:get("resource_group_injuryMedicine"),
        plural = locale:get("resource_group_injuryMedicine_plural"),
        resourceTypes = {
            resource.types.unfiredBowlInjuryMedicine.index,
            resource.types.firedBowlInjuryMedicine.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlInjuryMedicine,
    },
    {
        key = "burnMedicine",
        name = locale:get("resource_group_burnMedicine"),
        plural = locale:get("resource_group_burnMedicine_plural"),
        resourceTypes = {
            resource.types.unfiredBowlBurnMedicine.index,
            resource.types.firedBowlBurnMedicine.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlBurnMedicine,
    },
    {
        key = "foodPoisoningMedicine",
        name = locale:get("resource_group_foodPoisoningMedicine"),
        plural = locale:get("resource_group_foodPoisoningMedicine_plural"),
        resourceTypes = {
            resource.types.unfiredBowlFoodPoisoningMedicine.index,
            resource.types.firedBowlFoodPoisoningMedicine.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlFoodPoisoningMedicine,
    },
    {
        key = "virusMedicine",
        name = locale:get("resource_group_virusMedicine"),
        plural = locale:get("resource_group_virusMedicine_plural"),
        resourceTypes = {
            resource.types.unfiredBowlVirusMedicine.index,
            resource.types.firedBowlVirusMedicine.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.firedBowlVirusMedicine,
    },
    {
        key = "fertilizer",
        name = locale:get("resource_group_fertilizer"),
        plural = locale:get("resource_group_fertilizer_plural"),
        resourceTypes = {
            resource.types.manure.index,
            resource.types.compost.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.manure,
    },
    {
        key = "compostable",
        name = locale:get("resource_group_compostable"),
        plural = locale:get("resource_group_compostable_plural"),
        resourceTypes = {},
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.appleRotten,
    },
    {
        key = "rockSmallAny",
        name = locale:get("resource_group_rockSmallAny"),
        plural = locale:get("resource_group_rockSmallAny_plural"),
        resourceTypes = {
            resource.types.rockSmall.index,
            resource.types.rockSmallSoft.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.rockSmall,
    },
    {
        key = "rockAny",
        name = locale:get("resource_group_rockAny"),
        plural = locale:get("resource_group_rockAny_plural"),
        resourceTypes = {
            resource.types.rock.index,
            resource.types.rockSoft.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.rock,
    },
    {
        key = "stoneBlockAny",
        name = locale:get("resource_group_stoneBlockAny"),
        plural = locale:get("resource_group_stoneBlockAny_plural"),
        resourceTypes = {
            resource.types.stoneBlockSoft.index,
            resource.types.stoneBlockHard.index,
        },
        displayGameObjectTypeIndex = gameObjectTypeIndexMap.stoneBlock,
    },
})

function resource:createGroupHashesForBuiltInTypes()
    local validGroupTypes = typeMaps:createValidTypesArray("resourceGroup", resource.groups)
    for i,groupType in ipairs(validGroupTypes) do
        if not groupType.containsTypesSet then
            groupType.containsTypesSet = {}
        end
        for j, resourceTypeIndex in ipairs(groupType.resourceTypes) do
            groupType.containsTypesSet[resourceTypeIndex] = true
        end
    end
end

function resource:updateGroupContainedTypesHashForAddition(groupTypeIndex)
    local groupType = resource.groups[groupTypeIndex]
    if not groupType.containsTypesSet then
        groupType.containsTypesSet = {}
    end
    for i, resourceTypeIndex in ipairs(groupType.resourceTypes) do
        groupType.containsTypesSet[resourceTypeIndex] = true
    end
end

function resource:setSeedResourceTypeIndexes(seedResourceTypeIndexes)
    resource.groups.seed.resourceTypes = seedResourceTypeIndexes
    resource:updateGroupContainedTypesHashForAddition(resource.groups.seed.index)
end

function resource:groupOrResourceMatchesResource(groupOrResourceTypeIndex, resourceTypeIndex)
    if groupOrResourceTypeIndex == resourceTypeIndex then
        return true
    end
    local resourceGroup = resource.groups[groupOrResourceTypeIndex]
    if resourceGroup then
        return resourceGroup.containsTypesSet[resourceTypeIndex]
    end
    return false
end

function resource:placheolderKeyForGroupOrResource(groupOrResourceTypeIndex)
    local resourceGroup = resource.groups[groupOrResourceTypeIndex]
    if resourceGroup then
        return resourceGroup.key
    end
    return resource.types[groupOrResourceTypeIndex].key
end

function resource:stringForResourceTypeAndCount(typeIndex, count)
    local resourceType = resource.types[typeIndex]
    if count == 1 then
        return string.format("%d %s", count, resourceType.name)
    end

    return string.format("%d %s", count, resourceType.plural)
end

function resource:stringForResourceGroupTypeAndCount(groupTypeIndex, count)
    local resourceGroupType = resource.groups[groupTypeIndex]
    if count == 1 then
        return string.format("%d %s", count, resourceGroupType.name)
    end

    return string.format("%d %s", count, resourceGroupType.plural)
end


function resource:stringForResourceTypeAndCountWithRequiredCount(typeIndex, count, requiredCount)
    local resourceType = resource.types[typeIndex]
    if count == 1 then
        return string.format("%d/%d %s", count, requiredCount, resourceType.name)
    end

    return string.format("%d/%d %s", count, requiredCount, resourceType.plural)
end

function resource:outputStringFromOutputs(outputs)
    local outputsString = ""
    for resourceTypeIndex, count in pairs(outputs) do
        local resourceString = self:stringForResourceTypeAndCount(resourceTypeIndex, count)
        outputsString = outputsString .. resourceString
        if next(outputs, resourceTypeIndex) ~= nil then
            outputsString = outputsString .. ", "
        end
    end

    return outputsString
end

function resource:stringForListOfResourceTypes(resourceTypes)
    local outputsString = ""
    for i,resourceTypeIndex in ipairs(resourceTypes) do
        local resourceType = resource.types[resourceTypeIndex]
        local resourceString = resourceType.plural
        outputsString = outputsString .. resourceString
        if i < #resourceTypes then
            outputsString = outputsString .. ", "
        end
    end

    return outputsString
end

function resource:mjInit()
    resource.validTypes = typeMaps:createValidTypesArray("resource", resource.types)

    for i,resourceType in ipairs(resource.validTypes) do
        if resourceType.compostValue then
            table.insert(resource.groups.compostable.resourceTypes, resourceType.index)
        end
    end

    resource:createGroupHashesForBuiltInTypes()

    resource.alphabeticallyOrderedTypes = {}
    
    for i,resourceType in ipairs(resource.validTypes) do
        table.insert(resource.alphabeticallyOrderedTypes, resourceType)
    end
    
    local function sortByName(a,b)
        return a.name < b.name
    end

    table.sort(resource.alphabeticallyOrderedTypes, sortByName)
end

return resource